CREATE USER ersAdmin
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;
GRANT CONNECT TO ersAdmin;
GRANT RESOURCE TO ersAdmin;
GRANT CREATE SESSION TO ersAdmin;
GRANT CREATE TABLE TO ersAdmin;
GRANT CREATE VIEW TO ersAdmin;
conn ersAdmin/p4ssw0rd;

commit;